export default {
  WEBSITE_URL_LIVE: '',
  BACKEND_URL_LIVE: 'https://api.kundenzugang-recruiting.app/api/v1/',
  API_URL: 'https://azubi.api.digimonk.net/api/v1/',
  API_URL1: 'https://api.azubiregional.de/api/v1/',
  BASE_URL: 'https://azubi.api.digimonk.net/',
  ApiVersion: 8,
  TopBanner: '',
  TERMS_AND_CONDITIONS_URL: 'information/terms-and-condition?mobile=yes',
  PRIVACY_POLICY_URL: 'help/privacy-policy?mobile=yes',
  COOKIE_POLICY_URL: 'cookie-disclaimer?mobile=yes',
  LCode: -1,
  Bimage: '',
  _Base64String: '',
  token: '',
  userId: '',
  location: 'Select City',
};
